volumes:
  phpbb_config:
  phpbb_files:
  phpbb_store:
  phpbb_images:
  phpbb_ext:
  phpbb_styles:
  mysql_data:

networks:
  phpbb-net:
    driver: bridge

services:
  phpbb:
    image: evandarwin/phpbb:latest
    ports:
      - '8080:8080'
    environment:
      PHPBB_FORUM_NAME: My Amazing Forum
      PHPBB_FORUM_DESCRIPTION: Welcome to my phpBB forum
      PHPBB_USERNAME: admin
      PHPBB_PASSWORD: secure_password # <- CHANGE THIS!
      PHPBB_EMAIL: admin@example.com
      PHPBB_DATABASE_DRIVER: mysqli
      PHPBB_DATABASE_HOST: mysql
      PHPBB_DATABASE_NAME: phpbb
      PHPBB_DATABASE_USER: phpbb
      PHPBB_DATABASE_PASSWORD: mysql_password # <- CHANGE THIS!
      SERVER_NAME: forums.example.com
      COOKIE_SECURE: false
    volumes:
      - phpbb_config:/opt/phpbb/config  # other path: no typo! should only contain config.php
      - phpbb_files:/opt/phpbb/phpbb/files
      - phpbb_store:/opt/phpbb/phpbb/store
      - phpbb_images:/opt/phpbb/phpbb/images
      - phpbb_ext:/opt/phpbb/phpbb/ext  # optional
      - phpbb_styles:/opt/phpbb/phpbb/styles  # optional
    depends_on:
      - mysql
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - phpbb-net

  mysql:
    image: mariadb:latest
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: phpbb
      MARIADB_USER: phpbb
      MARIADB_PASSWORD: mysql_password # <- CHANGE THIS!
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - phpbb-net

